### ISSUE TITLE
I am getting error

### ISSUE THREAD

**Issue by deepikaguru** [aaronstone1699/parkinson-s-diagnosis#2]
Attribute error:- 'Sequential' object has no attribute 'classification_report'

**Comment by aaronstone1699** [comment]
could you please provide the stack trace

**Comment by deepikaguru** [comment]
Sir...am getting this error
What I have to do?
I am executing these code in Google colab

**Comment by aaronstone1699** [comment]
are you trying lesion_classifier.classification_report(),if so it wouldn't work as the model is built on keras sequential model while what youretrying to do is valid for a sklearn model
